### ISSUE TITLE
Missing source code for modern-di-faststream

### ISSUE THREAD

**Issue by jahermosilla** [modern-python/modern-di#60]
Hi, I've tried installing `modern-di-faststream` using `uv`, but the installed package does not contain the source code.

After investigating I believe the issue is caused by [this line](https://github.com/modern-python/modern-di/blob/main/packages/modern-di-faststream/pyproject.toml#L47) in pyproject.toml:

```toml
[tool.hatch.build]
include = ["modern_di_fastapi"]
```

Let me know if I can help further. Thanks for your work on this project!
